### ISSUE TITLE
Please allow verskion to be passed through cmake variables, instead of calling git

### ISSUE THREAD

**Issue by yurivict** [electronic-structure/SIRIUS#400]
```
--- CMakeFiles/generate_version_hpp.dir/all ---
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/science/sirius/work/SIRIUS-6.3.0/make_version_hpp.py", line 105, in <module>
    main()
  File "/wrkdirs/usr/ports/science/sirius/work/SIRIUS-6.3.0/make_version_hpp.py", line 96, in main
    branch_name = get_branch(sha_str, version_str)
  File "/wrkdirs/usr/ports/science/sirius/work/SIRIUS-6.3.0/make_version_hpp.py", line 69, in get_branch
    stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

When package is built, it builds from the tarball provided by GitHub. These tarballs don't contain .git directories.

**Comment by simonpintarelli** [comment]
Thanks for reporting. I think the problem here is that git is not found, which throws an exception that is not properly caught.
This should fix it: 7a509d3eacff91d9f7ed0b3577efbd1601a395d4

**Comment by yurivict** [comment]
The problem is that the version is not available other than potentially through a cmake variable.

**Comment by simonpintarelli** [comment]
If git is available on the system and if the sources were git cloned, the branch and commit sha will be read. Otherwise the version string stored in the file `./VERSION` is taken. If obtaining the SHA via `git` has failed, it will try to obtain the SHA from `api.github.com`, although this might return a wrong SHA in case a zip/tar was downloaded from an arbitrary commit.
IMO there is no need to have a CMake option to override the version manually.

**Comment by yurivict** [comment]
I provided the file ```VERSION``` in the source directory but it still fails because of missing ```git``` executable.

**Comment by simonpintarelli** [comment]
Which version did you download? Did you apply the patch  (7a509d3eacff91d9f7ed0b3577efbd1601a395d4) for the python script? If yes, could you please post the backtrace again?

**Comment by toxa81** [comment]
Dear @yurivict ! It should be possible now to build the library with and without `git` command and `.git` working folder. Can this issue be closed?

**Comment by yurivict** [comment]
I will try it, thanks!
